
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [6]:
import numpy as np

array = np.arange(10) # 0 t0 9
print(array)

# 2 to 10
array = np.arange(2,11)
print(array)

[0 1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [9]:
# Reshape
# 3 x 3

array = np.arange(1,10)
array

reshaped_array = array.reshape((3,3))
print(reshaped_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Access the element at the second row, second column.


In [11]:
print(reshaped_array[1,1])


5


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [14]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

# Addition
print(array1 + array2)

# Subtraction

print(array1 - array2)

# Multiplication

print(array1 * array2)

# Division
print(array1 / array2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].



In [17]:
array = np.array([1, 2, 3,4,5])

print(array.sum())

print(array.mean())

print(array.std())

15
3.0
1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [18]:
import numpy as np

# Original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshaped array
reshaped_array = original_array.reshape(2, 3)

print("Original array:")
print(original_array)
print("\nReshaped array:")
print(reshaped_array)


Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [23]:
import numpy as np

# Create a 5x5 array with random integers between 0 and 100
random_array = np.random.randint(50, 100, size=(5, 5))

print("Random 5x5 array:")
print(random_array)


Random 5x5 array:
[[67 75 91 77 62]
 [60 66 96 70 80]
 [51 94 53 99 85]
 [77 65 62 69 60]
 [55 93 82 55 84]]


Replace all values in the sub-array with a specific value.


In [26]:
random_array [:,:] = 10
print(random_array)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [20]:
import numpy as np

# Original array
original_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

# Extract the subarray
subarray = original_array[1:3]

print("Original array:")
print(original_array)
print("\nExtracted subarray:")
print(subarray)


Original array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Extracted subarray:
[[3 4]
 [5 6]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [30]:
import numpy as np

array = np.array([0,1,2])
print(array)

# title

new_array = np.tile(array, (3,1))
print(new_array)

[0 1 2]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [33]:
array_1d = np.array([0,1,2])

print(array_1d + new_array)

[[0 2 4]
 [0 2 4]
 [0 2 4]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [36]:
import numpy as np

random_array1 = np.random.randint(1,100, size = (3,3))
random_array2 = np.random.randint(1,100, size = (3,3))

# hstack 

concatenated_horizontally = np.hstack((random_array1, random_array2))
print(concatenated_horizontally)


[[15 49 92 77 68 88]
 [88 46  6 63 48 39]
 [13 97 87  9 29 21]]


In [37]:
# vstack
concatenated_vertically = np.vstack((random_array1, random_array2))
print(concatenated_vertically)


[[15 49 92]
 [88 46  6]
 [13 97 87]
 [77 68 88]
 [63 48 39]
 [ 9 29 21]]


In [48]:
# hsplit # vsplit

splittd_array1 = np.hsplit(concatenated_horizontally,2)
random_array1 = splittd_array1[0]
print(splittd_array1)

splittd_array2 = np.vsplit(concatenated_vertically,2)
random_array1 = splittd_array1[1]
print(splittd_array2)

[array([[15, 49, 92],
       [88, 46,  6],
       [13, 97, 87]]), array([[77, 68, 88],
       [63, 48, 39],
       [ 9, 29, 21]])]
[array([[15, 49, 92],
       [88, 46,  6],
       [13, 97, 87]]), array([[77, 68, 88],
       [63, 48, 39],
       [ 9, 29, 21]])]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [3]:
import numpy as np
array = np.array([1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5])

count_dict = {}

for i in array:
    if i in count_dict:
        count_dict[i] +=1
    else:
        count_dict[i] =1
print(count_dict)

{1: 7, 2: 5, 3: 1, 4: 1, 5: 2, 6: 1, 8: 1, 9: 1, 22: 1, 21: 1}


In [7]:
mode = None

max_count=0

for key, value in count_dict.items():
    if value> max_count:
        print(max_count, value, key)
        max_count = value
        mode = key
        print(max_count)
print(mode, max_count)

0 7 1
7
1 7


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

